FROM ubuntu:18.04

# # create git folder map folder first. map in docker compose file
RUN mkdir -p /root/gitfoldermap

# update & prereqs
RUN apt update && apt install -y \
    x11-apps \ 
    vim \ 
    rsync \
    git \
    net-tools \
    iputils-ping \
    nmap \
    samba-common-bin \
    arp-scan

# # install ip scanner & prereqs
# RUN apt update && \
#   apt install -y \
#   openjdk-8-jdk wget openjdk-8-jre gdebi
# RUN wget https://github.com/angryip/ipscan/releases/download/3.7.6/ipscan_3.7.6_all.deb && \
#   gdebi -n ipscan_3.7.6_all.deb

# install gstreamer 1.0
RUN DEBIAN_FRONTEND=noninteractive apt install -y \
  libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

## install deepstream python bindings prereqs 
RUN apt install -y \
    python3-gi \
    python3-dev \
    python3-gst-1.0 \
    python3-pip \
    python3-opencv \
    python3-numpy \
    libgstrtspserver-1.0-0 gstreamer1.0-rtsp \
    libgirepository1.0-dev \
    gobject-introspection \
    gir1.2-gst-rtsp-server-1.0 

## and deepstream python bindings
## WORKDIR /opt/nvidia/deepstream/deepstream-6.0/
# RUN cd sources && \
#   git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps && \
#   wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.0/pyds-1.1.0-py3-none-linux_aarch64.whl && \
#   pip3 install pyds-*-py3-none-linux_aarch64.whl