ARG ARCH=x86_64 
FROM nvcr.io/nvidia/deepstream:6.0-devel

# install prereqs & network packages
RUN apt update && apt install -y \
    x11-apps \ 
    vim \ 
    rsync \
    git \
    iputils-ping \
    net-tools \
    v4l-utils \
    openssh-server

# install gstreamer rtsp packages & gst python bindings
RUN apt install -y \
    python3-gi \
    python3-dev \
    python3-gst-1.0 \
    python3-pip \
    python3-opencv \
    python3-numpy \
    libgstrtspserver-1.0-0 gstreamer1.0-rtsp \
    libgirepository1.0-dev \
    gobject-introspection \
    gir1.2-gst-rtsp-server-1.0 \
    libgstreamer-plugins-base1.0-dev libjson-glib-dev libgstreamer1.0-dev 

# install deepstream python sample apps
WORKDIR /opt/nvidia/deepstream/deepstream-6.0/
RUN cd sources && \
  git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps && \
  wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.0/pyds-1.1.0-py3-none-linux_${ARCH}.whl && \
  pip3 install pyds-*-py3-none-linux_${ARCH}.whl

# setup non root user nvidia (password nvidia)
# RUN apt install -y sudo && \
#   useradd -m nvidia && echo "nvidia:nvidia" | chpasswd && adduser nvidia sudo
# RUN mkdir -p /home/nvidia/.ssh && chown -R nvidia:nvidia /home/nvidia/.ssh 
# USER nvidia